### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [Rv2719/ISII-WORKSHOPS-SISTEMA_CONTABLE_II#2]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by Rv2719** [comment]
Ok we will work on it. We will reproduce the issue.

**Comment by Rv2719** [comment]
We have categorized the issue

**Comment by jose598** [comment]
I got it.

**Comment by Rv2719** [comment]
We will proceed to process the request, @msdlc  will be the assigned analyst, @Rv2719 will develop the solution, and @PaulDBM will perform the tests

**Comment by jose598** [comment]
Thank you @Rv2719

**Comment by msdlc** [comment]
[Impact Analysis.docx](https://github.com/Rv2719/ISII-WORKSHOPS-SEPROAMERICA/files/7917126/Impact.Analysis.docx)
@jose598

**Comment by jose598** [comment]
Thank you. Start working on the issue please @msdlc

**Comment by Rv2719** [comment]
https://github.com/Rv2719/ISII-WORKSHOPS-SEPROAMERICA/blob/ee05a7b3ac34e82f1d6e23bffd524a5f91932a73/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L37-L59

**Comment by Rv2719** [comment]
There we have the solution.

https://github.com/Rv2719/ISII-WORKSHOPS-SEPROAMERICA/blob/ee05a7b3ac34e82f1d6e23bffd524a5f91932a73/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L1-L61

**Comment by jose598** [comment]
Yes, it looks good. 
Continue with the test plan

**Comment by PaulDBM** [comment]
[Test_Plan.docx](https://github.com/Rv2719/ISII-WORKSHOPS-SEPROAMERICA/files/7917440/Test_Plan.docx)
@jose598

**Comment by jose598** [comment]
I don't understand your test plan, everything is wrong?

**Comment by PaulDBM** [comment]
I forgot the results of the tests. I send the right file.
[Test_Plan.docx](https://github.com/Rv2719/ISII-WORKSHOPS-SEPROAMERICA/files/7917537/Test_Plan.docx)
.
@jose598

**Comment by jose598** [comment]
Ok, now it sounds good.
please continue with the release

**Comment by Rv2719** [comment]
Good. Now we have complete the solution. Now the programmer (me) will launch the new software version for you @jose598. @Rv2719

**Comment by Rv2719** [comment]
Well, so for you @jose598  can use the software just need go to the main page of this repository, and change to the branche "Issues_Management"
![image](https://user-images.githubusercontent.com/66104700/150623467-6f00e842-cf58-42ef-a6ac-0e7749f5a7ae.png)

Then you can download all the new version of the proyect in the "Code" button, you can download as ZIP
![image](https://user-images.githubusercontent.com/66104700/150623525-5bdda2da-3eeb-40a3-85d7-638c696e6436.png)

Then you unzip the proyect and open it with eclipse, so just have to run the main.java doc. 
![image](https://user-images.githubusercontent.com/66104700/150623566-44ba6451-19d1-41b7-b9b3-c9acd8b3f267.png)

And then you will see the program running.
![image](https://user-images.githubusercontent.com/66104700/150623585-b5e14116-360d-4aa1-afa2-c2e11dcd8e75.png)

Let me know if you need some help.  @jose598

**Comment by jose598** [comment]
OK, no worry. I already used.
I satisfy with the changes that you provided me.

**Comment by Rv2719** [comment]
Thanks
